#!/bin/sh
#
# delay-on-failure
#
# Originally from https://github.com/nextcloud/nextcloud-snap/blob/master/src/delay-on-failure/delay-on-failure

$*
if [ $? -ne 0 ]; then
	sleep 10 # Don't exit right away, so we'll be respawned
	exit 1
fi
exit 0
